### ISSUE TITLE
Strange attribute error

### ISSUE THREAD

**Issue by david314** [SilentSys/orhelper#12]
When trying to run the lazy example under Ubuntu, I got a strange attribute rror:

`python3 lazy.py
Traceback (most recent call last):
  File "/home/david/orhelper/examples/lazy.py", line 10, in <module>
    with orhelper.OpenRocketInstance() as instance:
  File "/home/david/.local/lib/python3.10/site-packages/orhelper/_orhelper.py", line 53, in __enter__
    self.openrocket = jpype.JPackage("net").sf.openrocket
AttributeError: Java package 'net' is not valid`

**Comment by david314** [comment]
I found the error, the CLASSPATH was not pointing correctly to the OpenRocket-15.03.jar!
